### PR TITLE
fix: adapt flags testing in test 6.1.1 and 6.1.4

### LINKED ISSUE #311: CSAF 2.0 `flags` not tested correctly
According to https://github.com/oasis-tcs/csaf/issues/909 (and also verified by tests in the `csaf-validator-lib` and `secvisogram`), we are missing the `flags` path in 6.1.1 and 6.1.4.

This is important.

### PR DESCRIPTION
**Pull request by domachine**
Closes #311 

There is probably some refactoring opportunity in both tests but I ignored this for this fix.

### CODE REVIEW

File: lib/mandatoryTests/mandatoryTest_6_1_1.js [hunk 1]
```diff
@@ -267,6 +272,32 @@ const collectProductRefsInRemediations = (
...
+ * @param {string} instancePath
+ * @param {{flags: any}} vulnerability
+ * @param {*} entries
+ */
+const collectProductRefsInFlags = (instancePath, vulnerability, entries) => {
+  const flags = vulnerability.flags
+  if (flags) {
+    for (let i = 0; i < flags.length; ++i) {
+      const remediation = flags[i]
+      const productIds = remediation.product_ids
```
Comment (tschmidtb51) [inline lib/mandatoryTests/mandatoryTest_6_1_1.js:285]: This sounds like a missed variable rename after copy-paste.
```suggestion
      const flag = flags[i]
      const productIds = flag.product_ids

**Review by tschmidtb51 — CHANGES_REQUESTED** [review]
Some minor variable naming things.

**Comment by domachine** [comment]
> Some minor variable naming things.

Good catch! Thank you!

**Review by tschmidtb51 — APPROVED** [review]
LGTM
