### PR TITLE
fix(CSAF2.1): Mandatory Test 6.1.2 Schema changed

### LINKED ISSUE #586: CSAF-2.1: Mandatory Test 6.1.2 Schema changed
https://github.com/oasis-tcs/csaf/blob/master/csaf_2.1/prose/share/csaf-v2.1-draft.md#612-multiple-definition-of-product-id-

### PR DESCRIPTION
**Pull request by bendo-eXX**

### CODE REVIEW

File: csaf_2_1/mandatoryTests/mandatoryTest_6_1_2.js [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+  function checkProductId(instancePath, productId) {
+    if (seenProductIds.has(productId)) {
+      ctx.isValid = false
+      ctx.errors.push({
+        instancePath,
+        message: 'duplicate definition of product_id',
+      })
+    } else {
+      seenProductIds.set(productId, instancePath)
+    }
```
Comment (domachine) [inline csaf_2_1/mandatoryTests/mandatoryTest_6_1_2.js:138]: Only the second (and later) occurrence is pushed into `errors`. The first occurrence is silently stored in `seenProductIds` and never reported. A user trying to fix a duplicate must manually search for the first occurrence.

File: csaf_2_1/mandatoryTests/mandatoryTest_6_1_2.js [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+   *
+   * @param {string} instancePath The instance path of the product_id to check.
+   * @param {string} productId The product_id value to check.
+   */
+  function checkProductId(instancePath, productId) {
+    if (seenProductIds.has(productId)) {
+      ctx.isValid = false
+      ctx.errors.push({
+        instancePath,
+        message: 'duplicate definition of product_id',
```
Comment (domachine) [inline csaf_2_1/mandatoryTests/mandatoryTest_6_1_2.js]: This test uses 'duplicate definition of product_id' while the CSAF 2.0 version uses 'duplicate definition product id' (note the missing underscore). Maybe we should keep this consistent.

**Review by domachine — DISMISSED** [review]
Found minor issues but already approved it. Feel free to fix and merge then.

**Review by domachine — APPROVED** [review]
LGTM
