### PR TITLE
fix(CSAF2.1): change schema for recommended test 6.2.8

### LINKED ISSUE #589: CSAF-2.1: Recommended Test 6.2.8 Schema changed
https://github.com/oasis-tcs/csaf/blob/master/csaf_2.1/prose/share/csaf-v2.1-draft.md#628-use-of-md5-as-the-only-hash-algorithm-

### PR DESCRIPTION
**Pull request by bendo-eXX**
https://github.com/oasis-tcs/csaf/blob/master/csaf_2.1/prose/share/csaf-v2.1-draft.md#628-use-of-md5-as-the-only-hash-algorithm-

### CODE REVIEW

File: csaf_2_1/recommendedTests/recommendedTest_6_2_8.js [hunk 1]
```diff
@@ -1,8 +1,9 @@
-import { optionalTest_6_2_8 } from '../../optionalTests.js'
+import checkForUnsafeHashAlgorithms from './shared/checkForUnsafeHashAlgorithms.js'
 
 /**
- * @param {unknown} doc
+ * This implements the recommended test 6.2.8 of the CSAF 2.1 standard.
+ * @param {any} doc
```
Comment (domachine) [inline csaf_2_1/recommendedTests/recommendedTest_6_2_8.js]: I'd keep `unknown` here as a type.

File: csaf_2_1/recommendedTests/shared/checkForUnsafeHashAlgorithms.js [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+        properties: {},
+      },
+    },
+  },
+})
+
+const validateHash = ajv.compile(hashSchema)
+
+/**
+ * @param {any} doc
```
Comment (domachine) [inline csaf_2_1/recommendedTests/shared/checkForUnsafeHashAlgorithms.js]: I think we're safer by using `unknown` here

File: csaf_2_1/shared/csafHelpers/walkHashes.js [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+const validateFullProductName = ajv.compile(fullProductNameSchema)
+const validateBranch = ajv.compile(branchSchema)
+const validateProductPath = ajv.compile(productPathSchema)
+
+/**
+ * @param {any} doc
+ * @param {(params: { path: string; hash: {} }) => void} onHashFound
+ */
+export function walkHashes(doc, onHashFound) {
+  if (!validateInput(doc)) {
```
Comment (domachine) [inline csaf_2_1/shared/csafHelpers/walkHashes.js:76]: Same here. I'd use `unknown`

**Review by domachine — APPROVED** [review]
